\# resume v1
.TH RJPC CV
.SH NAME
Ryan J.P. Casalino
.PP
.B E:
ryan@boringtranquility.io
.PP
.B P:
+1917.282.7506
.SH SYNOPSIS
I'm a programmer based in Seattle, WA. I'm largely self-taught with an unorthodox educational background. I'm had experience building server-side web applications such as Rails and Django. I've also had a hand in building RESTful API backend message systems expressed in JSON. Lastly, I've written dynamic web sites using JavaScript. I have a passion for learning and I am looking for opportunities that will foster my professional growth.
.SH TECHNICAL SKILLS
Programming languages I know:
.IP \[bu] 2
.B Go 
- 2 years
.IP \[bu]
.B Python 
- 3 years
.IP \[bu]
.B JavaScript 
- 4 years
.IP \[bu]
.BR Ruby 
- 1.5 year
\# glossary-style list 
.SS Tools Experience:
.PP
Databases (
.IR MySQL, 
.IR PostgreSQL, 
.IR MongoDB,
)
Cloud Providers (
.IR AWS, 
.IR Heroku
),
Operating Systems (
.IR Linux,
.IR macOS,
.IR Windows
),
Virtualization (
.IR Docker,
.IR minikube,
.IR VirtualBox
),
web servers (
.IR nginx,
\# char46 is a dot
.IR Apache
)\[char46]
My daily editor is
.IR vim,
my go-to OS is
.IR NixOS\[char46]
I self-host my personal websites and build them with a custom written static site generator. 
.SH EDUCATION
School of the Art Institute of Chicago - BFA, 2011
.SH WORK EXPERIENCE 
.TS
tab(:);
c s s
c | c | c
l | l | l.
Employment History
=
Company:Role:Duration 
_
React Mobile:Software Programmer:Jan 2019 - Nov 2019 (Contract)
_
GawkBox:Software Programmer:Aug 2017 - Jan 2019
_
Merchant-e Solutions:Software Developer:Nov 2016 - Jul 2017
_
Liaison Technologies:Software Developer:Oct 2015 - Nov 2016
_
Crescent City Schools:Operations & Technology Coordinator:Oct 2013 - Jul 2015
_
American Apparel:IT Coordinator:Aug 2011 - May 2013
.TE
.SH LINKS
.IP \[bu] 2
sourcehut (https://git.sr.ht/~rjpcasalino/)
.IP \[bu]
GitHub (https://github.com/rjpcasalino) 
.IP \[bu]
Lobsters (https://lobste.rs/u/rjpcasalino)
